
import { Level, Word, Sentence, GrammarPoint, ReadingArticle, QuizQuestion } from './types';

// DATA SET: A comprehensive subset of the 3500 words requested.
// This serves as the initial database for the application.

export const SAMPLE_WORDS: Word[] = [
  // ==========================================
  // LEVEL A1 (Existing)
  // ==========================================

  // --- A1: 问候 (Greetings) ---
  {
    id: "A1_001",
    french: "bonjour",
    ipa: "/bɔ̃.ʒuʁ/",
    chinese: "你好",
    part_of_speech: "感叹词",
    example: "Bonjour, comment allez-vous ?",
    example_chinese: "您好，您最近好吗？",
    level: Level.A1,
    category: "问候",
    tags: ["基础", "日常"],
    synonyms: ["salut"],
    antonyms: ["au revoir"]
  },
  {
    id: "A1_002",
    french: "salut",
    ipa: "/sa.ly/",
    chinese: "你好/再见",
    part_of_speech: "感叹词",
    example: "Salut ! Ça va ?",
    example_chinese: "嗨！你好吗？",
    level: Level.A1,
    category: "问候",
    tags: ["非正式", "日常"],
  },
  {
    id: "A1_003",
    french: "bonsoir",
    ipa: "/bɔ̃.swaʁ/",
    chinese: "晚上好",
    part_of_speech: "感叹词",
    example: "Bonsoir tout le monde.",
    example_chinese: "大家晚上好。",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_004",
    french: "bonne nuit",
    ipa: "/bɔn nɥi/",
    chinese: "晚安",
    part_of_speech: "感叹词",
    example: "Je vais dormir. Bonne nuit !",
    example_chinese: "我去睡了。晚安！",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_005",
    french: "au revoir",
    ipa: "/o ʁə.vwaʁ/",
    chinese: "再见",
    part_of_speech: "感叹词",
    example: "Au revoir et à bientôt.",
    example_chinese: "再见，回头见。",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_006",
    french: "merci",
    ipa: "/mɛʁ.si/",
    chinese: "谢谢",
    part_of_speech: "感叹词",
    example: "Merci beaucoup pour votre aide.",
    example_chinese: "非常感谢您的帮助。",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_007",
    french: "s'il vous plaît",
    ipa: "/sil vu plɛ/",
    chinese: "请 (您)",
    part_of_speech: "短语",
    example: "Un café, s'il vous plaît.",
    example_chinese: "请给我一杯咖啡。",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_008",
    french: "pardon",
    ipa: "/paʁ.dɔ̃/",
    chinese: "对不起/请原谅",
    part_of_speech: "感叹词",
    example: "Pardon, je ne comprends pas.",
    example_chinese: "对不起，我不明白。",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_009",
    french: "enchanté",
    ipa: "/ɑ̃.ʃɑ̃.te/",
    chinese: "幸会",
    part_of_speech: "形容词",
    example: "Enchanté de faire votre connaissance.",
    example_chinese: "很高兴认识您。",
    level: Level.A1,
    category: "问候",
  },
  {
    id: "A1_010",
    french: "à demain",
    ipa: "/a də.mɛ̃/",
    chinese: "明天见",
    part_of_speech: "短语",
    example: "Je dois partir. À demain !",
    example_chinese: "我得走了。明天见！",
    level: Level.A1,
    category: "问候",
  },

  // --- A1: 数字 (Numbers) ---
  {
    id: "A1_011",
    french: "un",
    ipa: "/œ̃/",
    chinese: "一",
    part_of_speech: "数词",
    example: "J'ai un frère.",
    example_chinese: "我有一个兄弟。",
    level: Level.A1,
    category: "数字",
  },
  {
    id: "A1_012",
    french: "deux",
    ipa: "/dø/",
    chinese: "二",
    part_of_speech: "数词",
    example: "Il est deux heures.",
    example_chinese: "现在是两点钟。",
    level: Level.A1,
    category: "数字",
  },
  {
    id: "A1_013",
    french: "trois",
    ipa: "/tʁwa/",
    chinese: "三",
    part_of_speech: "数词",
    example: "Jamais deux sans trois.",
    example_chinese: "好事成三 (谚语)。",
    level: Level.A1,
    category: "数字",
  },
  {
    id: "A1_014",
    french: "quatre",
    ipa: "/katʁ/",
    chinese: "四",
    part_of_speech: "数词",
    example: "Une table pour quatre personnes.",
    example_chinese: "一张四人桌。",
    level: Level.A1,
    category: "数字",
  },
  {
    id: "A1_015",
    french: "cinq",
    ipa: "/sɛ̃k/",
    chinese: "五",
    part_of_speech: "数词",
    example: "J'ai cinq minutes.",
    example_chinese: "我有五分钟时间。",
    level: Level.A1,
    category: "数字",
  },

  // --- A1: 颜色 (Colors) ---
  {
    id: "A1_016",
    french: "rouge",
    ipa: "/ʁuʒ/",
    chinese: "红色",
    part_of_speech: "形容词",
    example: "J'aime la couleur rouge.",
    example_chinese: "我喜欢红色。",
    level: Level.A1,
    category: "颜色",
  },
  {
    id: "A1_017",
    french: "bleu",
    ipa: "/blø/",
    chinese: "蓝色",
    part_of_speech: "形容词",
    example: "Le ciel est bleu aujourd'hui.",
    example_chinese: "今天天空是蓝色的。",
    level: Level.A1,
    category: "颜色",
  },
  {
    id: "A1_018",
    french: "vert",
    ipa: "/vɛʁ/",
    chinese: "绿色",
    part_of_speech: "形容词",
    example: "Les arbres sont verts.",
    example_chinese: "树是绿色的。",
    level: Level.A1,
    category: "颜色",
  },
  {
    id: "A1_019",
    french: "jaune",
    ipa: "/ʒon/",
    chinese: "黄色",
    part_of_speech: "形容词",
    example: "Le soleil est jaune.",
    example_chinese: "太阳是黄色的。",
    level: Level.A1,
    category: "颜色",
  },
  {
    id: "A1_020",
    french: "noir",
    ipa: "/nwaʁ/",
    chinese: "黑色",
    part_of_speech: "形容词",
    example: "Il porte un manteau noir.",
    example_chinese: "他穿着一件黑色大衣。",
    level: Level.A1,
    category: "颜色",
  },

  // --- A1: 家庭成员 (Family) ---
  {
    id: "A1_021",
    french: "père",
    ipa: "/pɛʁ/",
    chinese: "父亲",
    part_of_speech: "名词",
    gender: 'm',
    example: "Mon père est médecin.",
    example_chinese: "我父亲是医生。",
    level: Level.A1,
    category: "家庭",
  },
  {
    id: "A1_022",
    french: "mère",
    ipa: "/mɛʁ/",
    chinese: "母亲",
    part_of_speech: "名词",
    gender: 'f',
    example: "Ma mère cuisine très bien.",
    example_chinese: "我母亲做饭很好吃。",
    level: Level.A1,
    category: "家庭",
  },
  {
    id: "A1_023",
    french: "frère",
    ipa: "/fʁɛʁ/",
    chinese: "兄弟",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai un petit frère.",
    example_chinese: "我有一个弟弟。",
    level: Level.A1,
    category: "家庭",
  },
  {
    id: "A1_024",
    french: "sœur",
    ipa: "/sœʁ/",
    chinese: "姐妹",
    part_of_speech: "名词",
    gender: 'f',
    example: "Ma sœur habite à Lyon.",
    example_chinese: "我姐姐住在里昂。",
    level: Level.A1,
    category: "家庭",
  },
  {
    id: "A1_025",
    french: "famille",
    ipa: "/fa.mij/",
    chinese: "家庭",
    part_of_speech: "名词",
    gender: 'f',
    example: "J'aime passer du temps avec ma famille.",
    example_chinese: "我喜欢和家人共度时光。",
    level: Level.A1,
    category: "家庭",
  },

  // --- A1: 基础动词 (Verbs) ---
  {
    id: "A1_026",
    french: "être",
    ipa: "/ɛtʁ/",
    chinese: "是",
    part_of_speech: "动词",
    example: "Je suis étudiant.",
    example_chinese: "我是学生。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_027",
    french: "avoir",
    ipa: "/a.vwaʁ/",
    chinese: "有",
    part_of_speech: "动词",
    example: "J'ai faim.",
    example_chinese: "我饿了。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_028",
    french: "faire",
    ipa: "/fɛʁ/",
    chinese: "做",
    part_of_speech: "动词",
    example: "Qu'est-ce que tu fais ?",
    example_chinese: "你在做什么？",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_029",
    french: "aller",
    ipa: "/a.le/",
    chinese: "去",
    part_of_speech: "动词",
    example: "Je vais au cinéma.",
    example_chinese: "我去电影院。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_030",
    french: "venir",
    ipa: "/və.niʁ/",
    chinese: "来",
    part_of_speech: "动词",
    example: "Tu viens avec nous ?",
    example_chinese: "你跟我们一起来吗？",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_031",
    french: "manger",
    ipa: "/mɑ̃.ʒe/",
    chinese: "吃",
    part_of_speech: "动词",
    example: "Nous mangeons à midi.",
    example_chinese: "我们中午吃饭。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_032",
    french: "boire",
    ipa: "/bwaʁ/",
    chinese: "喝",
    part_of_speech: "动词",
    example: "Je veux boire de l'eau.",
    example_chinese: "我想喝水。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_033",
    french: "parler",
    ipa: "/paʁ.le/",
    chinese: "说话",
    part_of_speech: "动词",
    example: "Il parle français.",
    example_chinese: "他说法语。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_034",
    french: "aimer",
    ipa: "/e.me/",
    chinese: "爱/喜欢",
    part_of_speech: "动词",
    example: "J'aime le chocolat.",
    example_chinese: "我喜欢巧克力。",
    level: Level.A1,
    category: "动词",
  },
  {
    id: "A1_035",
    french: "habiter",
    ipa: "/a.bi.te/",
    chinese: "居住",
    part_of_speech: "动词",
    example: "J'habite à Paris.",
    example_chinese: "我住在巴黎。",
    level: Level.A1,
    category: "动词",
  },

  // --- A1: 食物饮料 (Food) ---
  {
    id: "A1_036",
    french: "pain",
    ipa: "/pɛ̃/",
    chinese: "面包",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'achète du pain tous les jours.",
    example_chinese: "我每天买面包。",
    level: Level.A1,
    category: "食物",
  },
  {
    id: "A1_037",
    french: "eau",
    ipa: "/o/",
    chinese: "水",
    part_of_speech: "名词",
    gender: 'f',
    example: "Une bouteille d'eau, s'il vous plaît.",
    example_chinese: "请给我一瓶水。",
    level: Level.A1,
    category: "食物",
  },
  {
    id: "A1_038",
    french: "lait",
    ipa: "/lɛ/",
    chinese: "牛奶",
    part_of_speech: "名词",
    gender: 'm',
    example: "Je bois du café au lait.",
    example_chinese: "我喝牛奶咖啡。",
    level: Level.A1,
    category: "食物",
  },
  {
    id: "A1_039",
    french: "pomme",
    ipa: "/pɔm/",
    chinese: "苹果",
    part_of_speech: "名词",
    gender: 'f',
    example: "Une pomme par jour éloigne le médecin.",
    example_chinese: "一天一苹果，医生远离我。",
    level: Level.A1,
    category: "食物",
  },
  {
    id: "A1_040",
    french: "café",
    ipa: "/ka.fe/",
    chinese: "咖啡",
    part_of_speech: "名词",
    gender: 'm',
    example: "Tu veux un café ?",
    example_chinese: "你要喝咖啡吗？",
    level: Level.A1,
    category: "食物",
  },

  // --- A1: 动物 (Animals) Sample ---
  {
    id: "A1_041",
    french: "chat",
    ipa: "/ʃa/",
    chinese: "猫",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le chat dort sur le lit.",
    example_chinese: "猫在床上睡觉。",
    level: Level.A1,
    category: "动物",
  },
  {
    id: "A1_042",
    french: "chien",
    ipa: "/ʃjɛ̃/",
    chinese: "狗",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai un chien noir.",
    example_chinese: "我有一只黑狗。",
    level: Level.A1,
    category: "动物",
  },

  // ==========================================
  // LEVEL A2 (Existing)
  // ==========================================

  // --- A2: 职业 (Professions) ---
  {
    id: "A2_001",
    french: "professeur",
    ipa: "/pʁɔ.fɛ.sœʁ/",
    chinese: "教师",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le professeur explique la leçon.",
    example_chinese: "老师正在讲解课文。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_002",
    french: "médecin",
    ipa: "/med.sɛ̃/",
    chinese: "医生",
    part_of_speech: "名词",
    gender: 'm',
    example: "Je dois voir un médecin.",
    example_chinese: "我得去看医生。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_003",
    french: "ingénieur",
    ipa: "/ɛ̃.ʒe.njœʁ/",
    chinese: "工程师",
    part_of_speech: "名词",
    gender: 'm',
    example: "Elle est ingénieur en informatique.",
    example_chinese: "她是计算机工程师。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_004",
    french: "avocat",
    ipa: "/a.vɔ.ka/",
    chinese: "律师",
    part_of_speech: "名词",
    gender: 'm',
    example: "Mon oncle est avocat.",
    example_chinese: "我的叔叔是律师。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_005",
    french: "infirmier",
    ipa: "/ɛ̃.fiʁ.mje/",
    chinese: "男护士",
    part_of_speech: "名词",
    gender: 'm',
    example: "L'infirmier aide les patients.",
    example_chinese: "护士帮助病人。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_006",
    french: "serveur",
    ipa: "/sɛʁ.vœʁ/",
    chinese: "服务员",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le serveur apporte le menu.",
    example_chinese: "服务员拿来了菜单。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_007",
    french: "secrétaire",
    ipa: "/sə.kʁe.tɛʁ/",
    chinese: "秘书",
    part_of_speech: "名词",
    gender: 'm',
    example: "La secrétaire répond au téléphone.",
    example_chinese: "秘书正在接电话。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_008",
    french: "directeur",
    ipa: "/di.ʁɛk.tœʁ/",
    chinese: "经理/主管",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il est le directeur de l'entreprise.",
    example_chinese: "他是公司的经理。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_009",
    french: "cuisinier",
    ipa: "/kɥi.zi.nje/",
    chinese: "厨师",
    part_of_speech: "名词",
    gender: 'm',
    example: "C'est un grand cuisinier français.",
    example_chinese: "他是一位伟大的法国厨师。",
    level: Level.A2,
    category: "职业",
  },
  {
    id: "A2_010",
    french: "policier",
    ipa: "/pɔ.li.sje/",
    chinese: "警察",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le policier dirige la circulation.",
    example_chinese: "警察正在指挥交通。",
    level: Level.A2,
    category: "职业",
  },

  // --- A2: 交通 (Transport) ---
  {
    id: "A2_011",
    french: "voiture",
    ipa: "/vwa.tyʁ/",
    chinese: "汽车",
    part_of_speech: "名词",
    gender: 'f',
    example: "Je vais au travail en voiture.",
    example_chinese: "我开车去上班。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_012",
    french: "train",
    ipa: "/tʁɛ̃/",
    chinese: "火车",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le train part à huit heures.",
    example_chinese: "火车八点出发。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_013",
    french: "avion",
    ipa: "/a.vjɔ̃/",
    chinese: "飞机",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai peur de prendre l'avion.",
    example_chinese: "我害怕坐飞机。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_014",
    french: "gare",
    ipa: "/ɡaʁ/",
    chinese: "火车站",
    part_of_speech: "名词",
    gender: 'f',
    example: "Rendez-vous à la gare.",
    example_chinese: "在火车站见面。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_015",
    french: "aéroport",
    ipa: "/a.e.ʁɔ.pɔʁ/",
    chinese: "机场",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il faut arriver tôt à l'aéroport.",
    example_chinese: "必须早点到机场。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_016",
    french: "métro",
    ipa: "/me.tʁo/",
    chinese: "地铁",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le métro parisien est pratique.",
    example_chinese: "巴黎地铁很方便。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_017",
    french: "bus",
    ipa: "/bys/",
    chinese: "公交车",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'attends le bus.",
    example_chinese: "我在等公交车。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_018",
    french: "taxi",
    ipa: "/tak.si/",
    chinese: "出租车",
    part_of_speech: "名词",
    gender: 'm',
    example: "Nous allons prendre un taxi.",
    example_chinese: "我们要坐出租车。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_019",
    french: "vélo",
    ipa: "/ve.lo/",
    chinese: "自行车",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il fait du vélo le dimanche.",
    example_chinese: "他星期天骑自行车。",
    level: Level.A2,
    category: "交通",
  },
  {
    id: "A2_020",
    french: "billet",
    ipa: "/bi.jɛ/",
    chinese: "票",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai acheté un billet d'avion.",
    example_chinese: "我买了一张机票。",
    level: Level.A2,
    category: "交通",
  },

  // --- A2: 情绪 (Emotions) ---
  {
    id: "A2_021",
    french: "heureux",
    ipa: "/œ.ʁø/",
    chinese: "幸福的/快乐的",
    part_of_speech: "形容词",
    example: "Ils sont très heureux ensemble.",
    example_chinese: "他们在一起很幸福。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_022",
    french: "triste",
    ipa: "/tʁist/",
    chinese: "悲伤的",
    part_of_speech: "形容词",
    example: "Pourquoi es-tu triste ?",
    example_chinese: "你为什么伤心？",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_023",
    french: "fatigué",
    ipa: "/fa.ti.ɡe/",
    chinese: "疲劳的",
    part_of_speech: "形容词",
    example: "Je suis fatigué après le travail.",
    example_chinese: "下班后我很累。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_024",
    french: "énervé",
    ipa: "/e.nɛʁ.ve/",
    chinese: "恼火的/生气的",
    part_of_speech: "形容词",
    example: "Il est énervé à cause du retard.",
    example_chinese: "他因为迟到而生气。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_025",
    french: "surpris",
    ipa: "/syʁ.pʁi/",
    chinese: "惊讶的",
    part_of_speech: "形容词",
    example: "Je suis surpris de te voir ici.",
    example_chinese: "我很惊讶在这里见到你。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_026",
    french: "inquiet",
    ipa: "/ɛ̃.kjɛ/",
    chinese: "担心的",
    part_of_speech: "形容词",
    example: "Ne sois pas inquiet.",
    example_chinese: "别担心。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_027",
    french: "calme",
    ipa: "/kalm/",
    chinese: "平静的",
    part_of_speech: "形容词",
    example: "Reste calme.",
    example_chinese: "保持冷静。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_028",
    french: "nerveux",
    ipa: "/nɛʁ.vø/",
    chinese: "紧张的",
    part_of_speech: "形容词",
    example: "Il est nerveux avant l'examen.",
    example_chinese: "考试前他很紧张。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_029",
    french: "déçu",
    ipa: "/de.sy/",
    chinese: "失望的",
    part_of_speech: "形容词",
    example: "Elle est déçue par les résultats.",
    example_chinese: "她对结果感到失望。",
    level: Level.A2,
    category: "情绪",
  },
  {
    id: "A2_030",
    french: "content",
    ipa: "/kɔ̃.tɑ̃/",
    chinese: "高兴的/满意的",
    part_of_speech: "形容词",
    example: "Je suis content de mon travail.",
    example_chinese: "我对我的工作很满意。",
    level: Level.A2,
    category: "情绪",
  },

  // --- A2: 天气 (Weather) ---
  {
    id: "A2_031",
    french: "soleil",
    ipa: "/sɔ.lɛj/",
    chinese: "太阳/阳光",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il y a du soleil aujourd'hui.",
    example_chinese: "今天阳光明媚。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_032",
    french: "pluie",
    ipa: "/plɥi/",
    chinese: "雨",
    part_of_speech: "名词",
    gender: 'f',
    example: "Je n'aime pas la pluie.",
    example_chinese: "我不喜欢下雨。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_033",
    french: "neige",
    ipa: "/nɛʒ/",
    chinese: "雪",
    part_of_speech: "名词",
    gender: 'f',
    example: "La neige tombe en hiver.",
    example_chinese: "冬天下雪。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_034",
    french: "vent",
    ipa: "/vɑ̃/",
    chinese: "风",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il y a beaucoup de vent.",
    example_chinese: "风很大。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_035",
    french: "nuage",
    ipa: "/nɥaʒ/",
    chinese: "云",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le ciel est couvert de nuages.",
    example_chinese: "天空布满了云。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_036",
    french: "chaud",
    ipa: "/ʃo/",
    chinese: "热的",
    part_of_speech: "形容词",
    example: "Il fait très chaud en été.",
    example_chinese: "夏天非常热。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_037",
    french: "froid",
    ipa: "/fʁwa/",
    chinese: "冷的",
    part_of_speech: "形容词",
    example: "J'ai froid.",
    example_chinese: "我很冷。",
    level: Level.A2,
    category: "天气",
  },
  {
    id: "A2_038",
    french: "météo",
    ipa: "/me.te.o/",
    chinese: "天气预报",
    part_of_speech: "名词",
    gender: 'f',
    example: "Quelle est la météo ?",
    example_chinese: "天气预报怎么说？",
    level: Level.A2,
    category: "天气",
  },

  // --- A2: 地点 (Places) ---
  {
    id: "A2_041",
    french: "restaurant",
    ipa: "/ʁɛs.tɔ.ʁɑ̃/",
    chinese: "餐厅",
    part_of_speech: "名词",
    gender: 'm',
    example: "On mange au restaurant ce soir ?",
    example_chinese: "今晚我们在餐厅吃饭吗？",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_042",
    french: "hôpital",
    ipa: "/ɔ.pi.tal/",
    chinese: "医院",
    part_of_speech: "名词",
    gender: 'm',
    example: "L'hôpital est près d'ici.",
    example_chinese: "医院离这儿很近。",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_043",
    french: "école",
    ipa: "/e.kɔl/",
    chinese: "学校",
    part_of_speech: "名词",
    gender: 'f',
    example: "Les enfants vont à l'école.",
    example_chinese: "孩子们去上学。",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_044",
    french: "parc",
    ipa: "/paʁk/",
    chinese: "公园",
    part_of_speech: "名词",
    gender: 'm',
    example: "Nous nous promenons dans le parc.",
    example_chinese: "我们在公园散步。",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_045",
    french: "banque",
    ipa: "/bɑ̃k/",
    chinese: "银行",
    part_of_speech: "名词",
    gender: 'f',
    example: "Je dois aller à la banque.",
    example_chinese: "我得去银行。",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_046",
    french: "poste",
    ipa: "/pɔst/",
    chinese: "邮局",
    part_of_speech: "名词",
    gender: 'f',
    example: "Où est la poste ?",
    example_chinese: "邮局在哪里？",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_047",
    french: "magasin",
    ipa: "/ma.ɡa.zɛ̃/",
    chinese: "商店",
    part_of_speech: "名词",
    gender: 'm',
    example: "Les magasins sont fermés le dimanche.",
    example_chinese: "商店周日关门。",
    level: Level.A2,
    category: "地点",
  },
  {
    id: "A2_048",
    french: "cinéma",
    ipa: "/si.ne.ma/",
    chinese: "电影院",
    part_of_speech: "名词",
    gender: 'm',
    example: "On va au cinéma ?",
    example_chinese: "我们去电影院吗？",
    level: Level.A2,
    category: "地点",
  },

  // --- A2: 动作 (Actions) ---
  {
    id: "A2_051",
    french: "marcher",
    ipa: "/maʁ.ʃe/",
    chinese: "走路",
    part_of_speech: "动词",
    example: "J'aime marcher dans la forêt.",
    example_chinese: "我喜欢在森林里走路。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_052",
    french: "courir",
    ipa: "/ku.ʁiʁ/",
    chinese: "跑步",
    part_of_speech: "动词",
    example: "Il court tous les matins.",
    example_chinese: "他每天早上跑步。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_053",
    french: "sauter",
    ipa: "/so.te/",
    chinese: "跳",
    part_of_speech: "动词",
    example: "Les enfants sautent de joie.",
    example_chinese: "孩子们高兴得跳了起来。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_054",
    french: "nager",
    ipa: "/na.ʒe/",
    chinese: "游泳",
    part_of_speech: "动词",
    example: "Je sais nager.",
    example_chinese: "我会游泳。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_055",
    french: "conduire",
    ipa: "/kɔ̃.dɥiʁ/",
    chinese: "驾驶",
    part_of_speech: "动词",
    example: "Il conduit prudemment.",
    example_chinese: "他开车很小心。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_056",
    french: "voyager",
    ipa: "/vwa.ja.ʒe/",
    chinese: "旅行",
    part_of_speech: "动词",
    example: "J'aime voyager en train.",
    example_chinese: "我喜欢坐火车旅行。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_057",
    french: "travailler",
    ipa: "/tʁa.va.je/",
    chinese: "工作",
    part_of_speech: "动词",
    example: "Je travaille beaucoup.",
    example_chinese: "我工作很努力。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_058",
    french: "étudier",
    ipa: "/e.ty.dje/",
    chinese: "学习",
    part_of_speech: "动词",
    example: "Elle étudie le français.",
    example_chinese: "她在学法语。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_059",
    french: "dormir",
    ipa: "/dɔʁ.miʁ/",
    chinese: "睡觉",
    part_of_speech: "动词",
    example: "Je dors huit heures par nuit.",
    example_chinese: "我每晚睡八小时。",
    level: Level.A2,
    category: "动作",
  },
  {
    id: "A2_060",
    french: "se réveiller",
    ipa: "/sə ʁe.vɛ.je/",
    chinese: "醒来",
    part_of_speech: "动词",
    example: "Je me réveille à 7 heures.",
    example_chinese: "我七点醒来。",
    level: Level.A2,
    category: "动作",
  },

  // ==========================================
  // LEVEL B1
  // ==========================================

  // --- B1: 工作职场 (Work) ---
  {
    id: "B1_001",
    french: "réunion",
    ipa: "/ʁe.y.njɔ̃/",
    chinese: "会议",
    part_of_speech: "名词",
    gender: 'f',
    example: "La réunion commence à 10 heures.",
    example_chinese: "会议十点开始。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_002",
    french: "collègue",
    ipa: "/kɔ.lɛɡ/",
    chinese: "同事",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai des collègues sympathiques.",
    example_chinese: "我的同事们很友好。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_003",
    french: "projet",
    ipa: "/pʁɔ.ʒɛ/",
    chinese: "项目",
    part_of_speech: "名词",
    gender: 'm',
    example: "Ce projet est très important.",
    example_chinese: "这个项目非常重要。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_004",
    french: "entreprise",
    ipa: "/ɑ̃.tʁə.pʁiz/",
    chinese: "企业/公司",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il travaille dans une grande entreprise.",
    example_chinese: "他在一家大公司工作。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_005",
    french: "compétence",
    ipa: "/kɔ̃.pe.tɑ̃s/",
    chinese: "能力/技能",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il a les compétences requises.",
    example_chinese: "他具备所需的能力。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_006",
    french: "salaire",
    ipa: "/sa.lɛʁ/",
    chinese: "工资",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le salaire est versé chaque mois.",
    example_chinese: "工资每月发放。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_007",
    french: "contrat",
    ipa: "/kɔ̃.tʁa/",
    chinese: "合同",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai signé mon contrat hier.",
    example_chinese: "我昨天签了合同。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_008",
    french: "responsabilité",
    ipa: "/ʁɛs.pɔ̃.sa.bi.li.te/",
    chinese: "责任",
    part_of_speech: "名词",
    gender: 'f',
    example: "C'est une grande responsabilité.",
    example_chinese: "这是一项重大的责任。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_009",
    french: "expérience",
    ipa: "/ɛks.pe.ʁjɑ̃s/",
    chinese: "经验/经历",
    part_of_speech: "名词",
    gender: 'f',
    example: "J'ai beaucoup d'expérience dans ce domaine.",
    example_chinese: "我在这个领域有很多经验。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_010",
    french: "carrière",
    ipa: "/ka.ʁjɛʁ/",
    chinese: "职业生涯",
    part_of_speech: "名词",
    gender: 'f',
    example: "Elle a une belle carrière.",
    example_chinese: "她有着美好的职业生涯。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_011",
    french: "chômage",
    ipa: "/ʃo.maʒ/",
    chinese: "失业",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le taux de chômage a baissé.",
    example_chinese: "失业率下降了。",
    level: Level.B1,
    category: "工作",
  },
  {
    id: "B1_012",
    french: "retraite",
    ipa: "/ʁə.tʁɛt/",
    chinese: "退休",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il prendra sa retraite l'année prochaine.",
    example_chinese: "他明年将退休。",
    level: Level.B1,
    category: "工作",
  },

  // --- B1: 学习教育 (Education) ---
  {
    id: "B1_020",
    french: "examen",
    ipa: "/ɛɡ.za.mɛ̃/",
    chinese: "考试",
    part_of_speech: "名词",
    gender: 'm',
    example: "J'ai réussi mon examen.",
    example_chinese: "我通过了考试。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_021",
    french: "diplôme",
    ipa: "/di.plom/",
    chinese: "文凭",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il a obtenu son diplôme.",
    example_chinese: "他获得了文凭。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_022",
    french: "recherche",
    ipa: "/ʁə.ʃɛʁʃ/",
    chinese: "研究",
    part_of_speech: "名词",
    gender: 'f',
    example: "Elle fait de la recherche scientifique.",
    example_chinese: "她从事科学研究。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_023",
    french: "université",
    ipa: "/y.ni.vɛʁ.si.te/",
    chinese: "大学",
    part_of_speech: "名词",
    gender: 'f',
    example: "L'université est fermée en août.",
    example_chinese: "大学八月份放假。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_024",
    french: "cours",
    ipa: "/kuʁ/",
    chinese: "课程",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le cours de français est intéressant.",
    example_chinese: "法语课很有趣。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_025",
    french: "connaissance",
    ipa: "/kɔ.nɛ.sɑ̃s/",
    chinese: "知识",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il a beaucoup de connaissances.",
    example_chinese: "他知识渊博。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_026",
    french: "méthode",
    ipa: "/me.tɔd/",
    chinese: "方法",
    part_of_speech: "名词",
    gender: 'f',
    example: "C'est une méthode efficace.",
    example_chinese: "这是一种有效的方法。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_027",
    french: "éducation",
    ipa: "/e.dy.ka.sjɔ̃/",
    chinese: "教育",
    part_of_speech: "名词",
    gender: 'f',
    example: "L'éducation est importante pour tous.",
    example_chinese: "教育对每个人都很重要。",
    level: Level.B1,
    category: "学习",
  },
  {
    id: "B1_028",
    french: "bourse",
    ipa: "/buʁs/",
    chinese: "奖学金",
    part_of_speech: "名词",
    gender: 'f',
    example: "Elle a reçu une bourse d'études.",
    example_chinese: "她获得了奖学金。",
    level: Level.B1,
    category: "学习",
  },

  // --- B1: 科学技术 (Technology) ---
  {
    id: "B1_030",
    french: "ordinateur",
    ipa: "/ɔʁ.di.na.tœʁ/",
    chinese: "电脑",
    part_of_speech: "名词",
    gender: 'm',
    example: "Mon ordinateur est en panne.",
    example_chinese: "我的电脑坏了。",
    level: Level.B1,
    category: "科技",
  },
  {
    id: "B1_031",
    french: "internet",
    ipa: "/ɛ̃.tɛʁ.nɛt/",
    chinese: "互联网",
    part_of_speech: "名词",
    gender: 'm',
    example: "Je cherche des informations sur internet.",
    example_chinese: "我在网上查找信息。",
    level: Level.B1,
    category: "科技",
  },
  {
    id: "B1_032",
    french: "logiciel",
    ipa: "/lɔ.ʒi.sjɛl/",
    chinese: "软件",
    part_of_speech: "名词",
    gender: 'm',
    example: "Ce logiciel est très utile.",
    example_chinese: "这个软件很有用。",
    level: Level.B1,
    category: "科技",
  },
  {
    id: "B1_033",
    french: "données",
    ipa: "/dɔ.ne/",
    chinese: "数据",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il faut protéger les données personnelles.",
    example_chinese: "必须保护个人数据。",
    level: Level.B1,
    category: "科技",
  },
  {
    id: "B1_034",
    french: "réseau",
    ipa: "/ʁe.zo/",
    chinese: "网络",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le réseau social est populaire.",
    example_chinese: "社交网络很受欢迎。",
    level: Level.B1,
    category: "科技",
  },
  {
    id: "B1_035",
    french: "numérique",
    ipa: "/ny.me.ʁik/",
    chinese: "数字的",
    part_of_speech: "形容词",
    example: "Nous vivons à l'ère numérique.",
    example_chinese: "我们生活在数字时代。",
    level: Level.B1,
    category: "科技",
  },
  {
    id: "B1_036",
    french: "fichier",
    ipa: "/fi.ʃje/",
    chinese: "文件",
    part_of_speech: "名词",
    gender: 'm',
    example: "Enregistrez le fichier.",
    example_chinese: "保存文件。",
    level: Level.B1,
    category: "科技",
  },

  // --- B1: 社会文化 (Society/Culture) ---
  {
    id: "B1_040",
    french: "culture",
    ipa: "/kyl.tyʁ/",
    chinese: "文化",
    part_of_speech: "名词",
    gender: 'f',
    example: "La culture française est riche.",
    example_chinese: "法国文化很丰富。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_041",
    french: "tradition",
    ipa: "/tʁa.di.sjɔ̃/",
    chinese: "传统",
    part_of_speech: "名词",
    gender: 'f',
    example: "C'est une vieille tradition.",
    example_chinese: "这是一个古老的传统。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_042",
    french: "société",
    ipa: "/sɔ.sje.te/",
    chinese: "社会/公司",
    part_of_speech: "名词",
    gender: 'f',
    example: "La société change rapidement.",
    example_chinese: "社会变化很快。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_043",
    french: "population",
    ipa: "/pɔ.py.la.sjɔ̃/",
    chinese: "人口",
    part_of_speech: "名词",
    gender: 'f',
    example: "La population augmente.",
    example_chinese: "人口在增加。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_044",
    french: "citoyen",
    ipa: "/si.twa.jɛ̃/",
    chinese: "公民",
    part_of_speech: "名词",
    gender: 'm',
    example: "Chaque citoyen a des droits.",
    example_chinese: "每个公民都有权利。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_045",
    french: "gouvernement",
    ipa: "/ɡu.vɛʁ.nə.mɑ̃/",
    chinese: "政府",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le gouvernement a annoncé une nouvelle loi.",
    example_chinese: "政府宣布了一项新法律。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_046",
    french: "loi",
    ipa: "/lwa/",
    chinese: "法律",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il faut respecter la loi.",
    example_chinese: "必须遵守法律。",
    level: Level.B1,
    category: "社会",
  },
  {
    id: "B1_047",
    french: "égalité",
    ipa: "/e.ɡa.li.te/",
    chinese: "平等",
    part_of_speech: "名词",
    gender: 'f',
    example: "Liberté, Égalité, Fraternité.",
    example_chinese: "自由，平等，博爱。",
    level: Level.B1,
    category: "社会",
  },

  // --- B1: 环境自然 (Environment) ---
  {
    id: "B1_050",
    french: "environnement",
    ipa: "/ɑ̃.vi.ʁɔn.mɑ̃/",
    chinese: "环境",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il faut protéger l'environnement.",
    example_chinese: "必须保护环境。",
    level: Level.B1,
    category: "环境",
  },
  {
    id: "B1_051",
    french: "pollution",
    ipa: "/pɔ.ly.sjɔ̃/",
    chinese: "污染",
    part_of_speech: "名词",
    gender: 'f',
    example: "La pollution de l'air est un problème.",
    example_chinese: "空气污染是一个问题。",
    level: Level.B1,
    category: "环境",
  },
  {
    id: "B1_052",
    french: "climat",
    ipa: "/kli.ma/",
    chinese: "气候",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le climat change.",
    example_chinese: "气候正在变化。",
    level: Level.B1,
    category: "环境",
  },
  {
    id: "B1_053",
    french: "nature",
    ipa: "/na.tyʁ/",
    chinese: "自然",
    part_of_speech: "名词",
    gender: 'f',
    example: "J'aime être dans la nature.",
    example_chinese: "我喜欢在大自然中。",
    level: Level.B1,
    category: "环境",
  },
  {
    id: "B1_054",
    french: "écologie",
    ipa: "/e.kɔ.lɔ.ʒi/",
    chinese: "生态",
    part_of_speech: "名词",
    gender: 'f',
    example: "L'écologie est une science.",
    example_chinese: "生态学是一门科学。",
    level: Level.B1,
    category: "环境",
  },
  {
    id: "B1_055",
    french: "recyclage",
    ipa: "/ʁə.si.klaʒ/",
    chinese: "回收",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le recyclage est important.",
    example_chinese: "回收利用很重要。",
    level: Level.B1,
    category: "环境",
  },

  // --- B1: 经济商业 (Economics) ---
  {
    id: "B1_060",
    french: "économie",
    ipa: "/e.kɔ.nɔ.mi/",
    chinese: "经济",
    part_of_speech: "名词",
    gender: 'f',
    example: "L'économie mondiale est en crise.",
    example_chinese: "世界经济陷入危机。",
    level: Level.B1,
    category: "经济",
  },
  {
    id: "B1_061",
    french: "marché",
    ipa: "/maʁ.ʃe/",
    chinese: "市场",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le marché du travail est difficile.",
    example_chinese: "就业市场很困难。",
    level: Level.B1,
    category: "经济",
  },
  {
    id: "B1_062",
    french: "budget",
    ipa: "/byd.ʒɛ/",
    chinese: "预算",
    part_of_speech: "名词",
    gender: 'm',
    example: "Nous avons un budget limité.",
    example_chinese: "我们的预算有限。",
    level: Level.B1,
    category: "经济",
  },
  {
    id: "B1_063",
    french: "prix",
    ipa: "/pʁi/",
    chinese: "价格",
    part_of_speech: "名词",
    gender: 'm',
    example: "Les prix augmentent.",
    example_chinese: "价格在上涨。",
    level: Level.B1,
    category: "经济",
  },
  {
    id: "B1_064",
    french: "consommateur",
    ipa: "/kɔ̃.sɔ.ma.tœʁ/",
    chinese: "消费者",
    part_of_speech: "名词",
    gender: 'm',
    example: "Le consommateur a le choix.",
    example_chinese: "消费者有选择权。",
    level: Level.B1,
    category: "经济",
  },
  {
    id: "B1_065",
    french: "impôt",
    ipa: "/ɛ̃.po/",
    chinese: "税",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il faut payer ses impôts.",
    example_chinese: "必须纳税。",
    level: Level.B1,
    category: "经济",
  },

  // --- B1: 抽象概念 (Abstract) ---
  {
    id: "B1_070",
    french: "liberté",
    ipa: "/li.bɛʁ.te/",
    chinese: "自由",
    part_of_speech: "名词",
    gender: 'f',
    example: "La liberté est précieuse.",
    example_chinese: "自由是珍贵的。",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_071",
    french: "justice",
    ipa: "/ʒys.tis/",
    chinese: "正义/司法",
    part_of_speech: "名词",
    gender: 'f',
    example: "Nous demandons justice.",
    example_chinese: "我们要求正义。",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_072",
    french: "bonheur",
    ipa: "/bɔ.nœʁ/",
    chinese: "幸福",
    part_of_speech: "名词",
    gender: 'm',
    example: "L'argent ne fait pas le bonheur.",
    example_chinese: "金钱买不到幸福。",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_073",
    french: "espoir",
    ipa: "/ɛs.pwaʁ/",
    chinese: "希望",
    part_of_speech: "名词",
    gender: 'm',
    example: "Il y a toujours de l'espoir.",
    example_chinese: "总是有希望的。",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_074",
    french: "vérité",
    ipa: "/ve.ʁi.te/",
    chinese: "真理/真相",
    part_of_speech: "名词",
    gender: 'f',
    example: "Dites la vérité.",
    example_chinese: "说实话。",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_075",
    french: "idée",
    ipa: "/i.de/",
    chinese: "主意/想法",
    part_of_speech: "名词",
    gender: 'f',
    example: "J'ai une bonne idée.",
    example_chinese: "我有一个好主意。",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_076",
    french: "opinion",
    ipa: "/ɔ.pi.njɔ̃/",
    chinese: "观点",
    part_of_speech: "名词",
    gender: 'f',
    example: "Quelle est votre opinion ?",
    example_chinese: "您的观点是什么？",
    level: Level.B1,
    category: "抽象",
  },
  {
    id: "B1_077",
    french: "réalité",
    ipa: "/ʁe.a.li.te/",
    chinese: "现实",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il faut affronter la réalité.",
    example_chinese: "必须面对现实。",
    level: Level.B1,
    category: "抽象",
  },

  // ==========================================
  // LEVEL B2 (Existing Sample)
  // ==========================================
  {
    id: "B2_001",
    french: "ambiguïté",
    ipa: "/ɑ̃.bi.ɡɥi.te/",
    chinese: "歧义",
    part_of_speech: "名词",
    gender: 'f',
    example: "Il faut lever l'ambiguïté de cette phrase.",
    example_chinese: "必须消除这句话的歧义。",
    level: Level.B2,
    category: "高级抽象",
  },

  // ==========================================
  // LEVEL C1 (Existing Sample)
  // ==========================================
  {
    id: "C1_001",
    french: "épistémologie",
    ipa: "/e.pis.te.mɔ.lɔ.ʒi/",
    chinese: "认识论",
    part_of_speech: "名词",
    gender: 'f',
    example: "C'est une question d'épistémologie complexe.",
    example_chinese: "这是一个复杂的认识论问题。",
    level: Level.C1,
    category: "高级学术",
  }
];

export const SAMPLE_SENTENCES: Sentence[] = [
  {
    id: "SENT_001",
    category: "问候",
    subcategory: "基本问候",
    french: "Bonjour, comment allez-vous ?",
    ipa: "/bɔ̃.ʒuʁ, kɔ.mɑ̃ a.le vu/",
    chinese: "您好，您最近好吗？",
    level: Level.A1,
    situation: "正式场合问候",
    notes: "正式场合使用，对陌生人或长辈",
    alternative: ["Salut, ça va ?"]
  },
  {
    id: "SENT_002",
    category: "餐厅",
    subcategory: "点菜",
    french: "Je voudrais le menu, s'il vous plaît.",
    ipa: "/ʒə vu.dʁɛ lə mə.ny, sil vu plɛ/",
    chinese: "我想要菜单，谢谢。",
    level: Level.A1,
    situation: "餐厅点餐",
  },
  {
    id: "SENT_003",
    category: "社交",
    subcategory: "感谢",
    french: "Je vous remercie infiniment pour votre aide.",
    ipa: "/ʒə vu ʁə.mɛʁ.si ɛ̃.fi.ni.mɑ̃ puʁ vɔtʁ ɛd/",
    chinese: "非常感谢您的帮助。",
    level: Level.B1,
    situation: "正式感谢",
  }
];

export const SAMPLE_GRAMMAR: GrammarPoint[] = [
  {
    id: "GRAM_001",
    category: "冠词",
    title: "定冠词 (Les articles définis)",
    level: Level.A1,
    explanation: "定冠词用于指代特定或已知的人或事物。相当于英语的 'the'。",
    rules: [
      "阳性单数名词前用 le",
      "阴性单数名词前用 la",
      "复数名词前用 les",
      "以元音或哑音h开头的单数名词前用 l'"
    ],
    examples: [
      { french: "Le livre", chinese: "这本书" },
      { french: "La maison", chinese: "这所房子" },
      { french: "Les enfants", chinese: "孩子们" },
      { french: "L'école", chinese: "学校" }
    ],
    exceptions: [
        { case: "国家名前", example: "Je vais en France.", explanation: "阴性国家名前用en，不用冠词" }
    ],
    common_mistakes: ["错误：La livre ✓ 正确：Le livre"]
  },
  {
    id: "GRAM_002",
    category: "动词",
    title: "复合过去时 (Passé Composé)",
    level: Level.A2,
    explanation: "表示过去发生的动作，已完成。",
    rules: [
      "由助动词(avoir/être)的现在时 + 过去分词构成",
      "大多数动词使用avoir作为助动词",
      "位移动词和代词式动词使用être"
    ],
    examples: [
      { french: "J'ai mangé", chinese: "我吃了" },
      { french: "Je suis allé(e)", chinese: "我去了" }
    ]
  }
];

export const SAMPLE_ARTICLES: ReadingArticle[] = [
  {
    id: "READ_001",
    title: "Une journée à Paris",
    level: Level.A2,
    word_count: 300,
    reading_time: "2分钟",
    content: "Marc habite à Paris depuis deux ans. Aujourd'hui, il se lève tôt car c'est samedi. Il adore le week-end. D'abord, il va à la boulangerie pour acheter des croissants et une baguette traditionnelle. L'odeur du pain chaud est magnifique. Ensuite, il prend le métro pour aller au musée du Louvre. Il aime beaucoup l'art. À midi, il déjeune dans un petit restaurant près de la Seine. L'après-midi, il se promène dans le jardin des Tuileries. Le soir, il retrouve ses amis pour le dîner.",
    translation: "马克住在巴黎已经两年了。今天他起得很早，因为是星期六。他热爱周末。首先，他去面包店买羊角面包和一根传统法棍。热面包的香味太棒了。然后，他坐地铁去卢浮宫博物馆。他非常喜欢艺术。中午，他在塞纳河附近的一家小餐馆吃午饭。下午，他在杜乐丽花园散步。晚上，他和朋友们见面吃晚饭。",
    vocabulary: [
      { french: "habite", chinese: "居住 (habiter)", ipa: "/a.bit/", part_of_speech: "动词" },
      { french: "boulangerie", chinese: "面包店", ipa: "/bu.lɑ̃.ʒʁi/", part_of_speech: "名词" },
      { french: "magnifique", chinese: "极好的", ipa: "/ma.ɲi.fik/", part_of_speech: "形容词" }
    ],
    questions: [
      {
        id: "Q_001",
        question: "Marc habite où ?",
        options: ["À Lyon", "À Paris", "À Marseille", "À Bordeaux"],
        correct_answer: 1,
        explanation: "文中第一句提到 'Marc habite à Paris'."
      },
      {
        id: "Q_002",
        question: "Que fait-il le matin ?",
        options: ["Il dort", "Il travaille", "Il va à la boulangerie", "Il regarde la télé"],
        correct_answer: 2,
        explanation: "文中提到 'D'abord, il va à la boulangerie'."
      }
    ],
    cultural_notes: ["巴黎的面包店（Boulangerie）是法国生活的重要组成部分，法棍（Baguette）是必不可少的主食。"],
    grammar_points: [{ point: "depuis + 时间", explanation: "表示动作从过去持续到现在" }]
  }
];

export const SAMPLE_QUIZ: QuizQuestion[] = [
  {
    id: "QUIZ_001",
    type: "vocab",
    level: Level.A1,
    question: "Bonjour 是什么意思？",
    options: ["再见", "你好", "谢谢", "对不起"],
    correctAnswer: 1,
    explanation: "Bonjour 是法语中最常用的问候语，意为'你好'。"
  },
  {
    id: "QUIZ_002",
    type: "grammar",
    level: Level.A1,
    question: "请选择正确的定冠词：___ chat (阳性)",
    options: ["La", "Le", "Les", "L'"],
    correctAnswer: 1,
    explanation: "chat 是阳性单数名词，所以使用 Le。"
  },
  {
    id: "QUIZ_003",
    type: "listening",
    level: Level.A1,
    question: "听到的单词 'Rouge' 是什么颜色？",
    options: ["蓝色", "绿色", "红色", "黄色"],
    correctAnswer: 2,
    explanation: "Rouge 意为红色。"
  }
];
